### ISSUE TITLE
Why did you create nebula?

### ISSUE THREAD

**Issue by sukhchainn** [gscept/nebula#4]
Why created nebula when there are many open source, MIT licensed Game engines already available out there? Why not create a 3D modeling tool or an animation tool that people need the most right now?

In today's date designers are also learning to code and they want a designer tool in which they can create their own filters and effects and call them as commands form inbuilt integrated terminal. So yet again, why this when you could have done anything else?

**Comment by Duttenheim** [comment]
You are welcome to fork Nebula and make it into a 3D modelling tool if you want :) The rendering subsystem could probably work just as it is, and can be ripped out for reuse. 

The reason we started working on this new version was because we had some ideas about designing a game engine which put emphasis on memory layouts and performance. We also aim for the engine to be easy to use and intuitive, instead of having to understand deep class hierarchies and the like, most of the engine API is just a very simple facade of providing IDs and parameters, which in turn makes the engine easy to expose to scripting and code hot reloading. 

On the rendering side, we wanted to design a rendering system which was optimal for the new rendering APIs like Vulkan/DX12/Metal.

**Comment by sukhchainn** [comment]
So, I can fork i make an animation or video editing tool out of it?
Is the documentation complete?

**Comment by Duttenheim** [comment]
Depends on what you mean by complete documentation. Some parts of the subsystems in the rendering is explained thoroughly, but most of the documentation is in the code. Every function and file is described, and there is a Doxygen settings file you can just run to generate an index of the documentation. 

You can fork and use it for whatever you want, it's completely free for you to do with as you wish.

**Comment by sukhchainn** [comment]
@Duttenheim I will try to read the code base. If I got an understanding of the code and if it's possible then I will use it to make an animation tool. I will give proper credits to you so don't worry.
